AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

MethodLength:
  CountComments: true 
  Max: 30

Metrics/AbcSize:
  Max: 25
